Feature/jwt and swagger
Wittelsbach-Konig/PreCrime_Reborn pull request #3
Opened 2023-11-13 17:10 UTC by Wittelsbach-Konig

Вторая работающая версия бэкенда

2023-11-13 19:18 UTC, ArtKhud00 requested changes

2023-11-13 19:18 UTC, ArtKhud00 commented on backend/src/main/java/ru/itmo/precrimeupd/security/SecurityLiterals.java
> +    public static final String DETECTIVE_ENDPOINTS = "/api/v1/**";
Надо указать endpoints в соответствии с ролями. Например так     

private static final String[] REACT_GROUP_BOSS_ENDPOINTs = {"/api/v1/reactiongroup/**"};

    private static final String[] ADMIN_ENDPOINTs = {"/api/v1/admin",
                                                    "/api/v1/visions/add"};

    private static final String[] TECHNIC_ENDPOINTs = {"/api/v1/precogs/**",
                                                        "/api/v1/visions/{id}/accept"};


    private static final String[] DETECTIVE_ENDPOINTs = {"/api/v1/cards/randomDateTime",
                                                        "/api/v1/cards/randomVictimName",
                                                        "/api/v1/cards/randomCriminalName",
                                                        "/api/v1/cards/newcard"};

    private static final String[] COMMON_VISION_ENDPOINTS = {"/api/v1/visions", "/api/v1/visions/{id}"};

    private static final String[] COMMON_CARDS_ENDPOINTS = {"/api/v1/cards",
                                                           "/api/v1/cards/{id}"};

2023-11-13 19:18 UTC, ArtKhud00 commented on backend/src/main/java/ru/itmo/precrimeupd/security/SecurityLiterals.java
> +    public static final String DETECTIVE_ENDPOINTS = "/api/v1/**";
Только надо учесть, что у детектива должен быть доступен просмотр списка видений и отдельного видения
Техник может просматривать список видений и отдельное видение, кроме того он может оперировать видениями
Аудитор имеет доступ к списку карточек и к отдельной карточке
Лучше свериться с контроллерами

2023-11-13 21:36 UTC, Wittelsbach-Konig commented on backend/src/main/java/ru/itmo/precrimeupd/security/SecurityLiterals.java
> +    public static final String DETECTIVE_ENDPOINTS = "/api/v1/**";
Изменил, проверь пожалуйста

2023-11-14 11:43 UTC, ArtKhud00 approved these changes

2023-11-14 11:43 UTC, merged